{
    "status": true,
    "message": "All requests for quotations fetched successfully",
    "data": {
        "current_page": 1,
        "data": [
            {
                "id": 1,
                "subscriber_id": 1,
                "procurement_id": 4,
                "project_id": 1,
                "rfq_code": "298388",
                "title": "Need Engineering Tools",
                "procurement_type": "MIV-IR",
                "client_project_department": "Engineering",
                "vendor_category_id": null,
                "budget": 500000,
                "currency": "NGN",
                "bid_count": 0,
                "delivery_date": "2024-12-20",
                "bidding_deadline": "2024-09-20",
                "status": "sent",
                "deleted_at": null,
                "created_at": "2024-08-12T10:45:10.000000Z",
                "updated_at": "2024-08-12T11:01:25.000000Z",
                "subscriber": {
                    "id": 1,
                    "plan_id": 1,
                    "name": "Westfield",
                    "address": "Bonny Island",
                    "phone_number": "08100800359",
                    "created_at": "2024-08-03T12:17:53.000000Z",
                    "updated_at": "2024-08-03T12:17:53.000000Z",
                    "deleted_at": null
                },
                "project": {
                    "id": 1,
                    "project_name": "DLB Kennena",
                    "project_title": "Exhibit",
                    "project_duration": "113 days",
                    "project_start_date": "2024-12-12",
                    "project_end_date": "2025-04-04",
                    "project_description": "This is for wesfiled drill",
                    "project_manager_id": 1,
                    "subscriber_id": 1,
                    "status": "active",
                    "created_at": "2024-08-05T16:19:25.000000Z",
                    "updated_at": "2024-08-05T16:19:25.000000Z",
                    "deleted_at": null
                },
                "procurement_requisition": {
                    "id": 4,
                    "subscriber_id": 1,
                    "department_id": 1,
                    "requested_by": 4,
                    "batch_code": "298388",
                    "requisition_type": "MIV-IR",
                    "requisition_title": "Need Engineering Tools",
                    "barge_master_approver_id": 3,
                    "barge_master_approved_at": "2024-08-12 10:45:10",
                    "barge_master_status": "approved",
                    "comment": "Will be provided",
                    "status": "approved",
                    "deleted_at": null,
                    "created_at": "2024-08-08T13:45:39.000000Z",
                    "updated_at": "2024-08-12T10:45:10.000000Z",
                    "requisitions": [
                        {
                            "id": 8,
                            "subscriber_id": 1,
                            "procurement_id": 4,
                            "inventoryable_type": "App\\Models\\SparePartEngine",
                            "inventoryable_id": 1,
                            "type": "sparepart",
                            "barge_category": "engine",
                            "barge_asset": "generator",
                            "barge_asset_id": 1,
                            "uom_id": 1,
                            "description": "this is a huisman crane",
                            "part_number": null,
                            "model_number": null,
                            "stock_quantity": 50,
                            "critical_level": "high",
                            "threshold": 5,
                            "status": "pending",
                            "reason_for_removal": null,
                            "remark": null,
                            "created_at": "2024-08-08T13:45:39.000000Z",
                            "updated_at": "2024-08-08T13:45:39.000000Z",
                            "inventoryable": {
                                "id": 1,
                                "subscriber_id": 1,
                                "project_id": null,
                                "barge_id": null,
                                "deck_id": 1,
                                "keystore_id": 1,
                                "stock_quantity": 70,
                                "critical_level": "high",
                                "threshold": 5,
                                "uom_id": 1,
                                "location_id": 1,
                                "vendor_id": 1,
                                "part_number": "456-kla",
                                "model_number": "arr-675",
                                "description": "this is a huisman crane",
                                "sparepart_engine_category_id": 1,
                                "barge_equipment_id": 1,
                                "safety_category_id": 1,
                                "added_by": 1,
                                "date_acquired": "2024-06-25",
                                "waranty_period": "2024-12-25",
                                "status": "active",
                                "remark": "this is good",
                                "created_at": "2024-08-05T16:21:30.000000Z",
                                "updated_at": "2024-08-08T12:57:27.000000Z",
                                "deleted_at": null
                            },
                            "attachements": [
                                {
                                    "id": 6,
                                    "procurement_requisition_id": 8,
                                    "attachement": "1723124739_EHPmAeBihV.jpg",
                                    "created_at": "2024-08-08T13:45:39.000000Z",
                                    "updated_at": "2024-08-08T13:45:39.000000Z",
                                    "attachement_url": "http://127.0.0.1:8000/storage/requisition_images/1723124739_EHPmAeBihV.jpg"
                                }
                            ]
                        },
                        {
                            "id": 9,
                            "subscriber_id": 1,
                            "procurement_id": 4,
                            "inventoryable_type": "App\\Models\\DeckConsumable",
                            "inventoryable_id": 1,
                            "type": "consumable",
                            "barge_category": "deck",
                            "barge_asset": "Paintings",
                            "barge_asset_id": 1,
                            "uom_id": 1,
                            "description": "awesome grid",
                            "part_number": null,
                            "model_number": null,
                            "stock_quantity": 45,
                            "critical_level": "medium",
                            "threshold": 5,
                            "status": "pending",
                            "reason_for_removal": null,
                            "remark": null,
                            "created_at": "2024-08-08T13:45:39.000000Z",
                            "updated_at": "2024-08-08T13:45:39.000000Z",
                            "inventoryable": {
                                "id": 1,
                                "subscriber_id": 1,
                                "project_id": 1,
                                "barge_id": 1,
                                "deck_id": 1,
                                "vendor_id": 1,
                                "keystore_id": 1,
                                "barge_component_category_id": 1,
                                "location_id": 1,
                                "oil_and_lubricant_type_id": 1,
                                "unit_of_measurement_id": 1,
                                "consumable_deck_category_id": 1,
                                "description": "awesome grid",
                                "part_number": "ADE-5674",
                                "model_grade": "ADD-6534",
                                "stock_quantity": 50,
                                "threshold": 10,
                                "status_condition": "healthy",
                                "critical_level": "low",
                                "added_by": 1,
                                "date_acquired": "2024-01-25",
                                "waranty_period": "2025-06-25",
                                "status": "active",
                                "remark": "this is work in progress",
                                "created_at": "2024-08-07T14:12:05.000000Z",
                                "updated_at": "2024-08-07T14:12:05.000000Z",
                                "deleted_at": null
                            },
                            "attachements": [
                                {
                                    "id": 7,
                                    "procurement_requisition_id": 9,
                                    "attachement": "1723124739_eF7FFsmpxj.jpeg",
                                    "created_at": "2024-08-08T13:45:39.000000Z",
                                    "updated_at": "2024-08-08T13:45:39.000000Z",
                                    "attachement_url": "http://127.0.0.1:8000/storage/requisition_images/1723124739_eF7FFsmpxj.jpeg"
                                }
                            ]
                        },
                        {
                            "id": 10,
                            "subscriber_id": 1,
                            "procurement_id": 4,
                            "inventoryable_type": "App\\Models\\DeckConsumable",
                            "inventoryable_id": 2,
                            "type": "consumable",
                            "barge_category": "deck",
                            "barge_asset": "Paintings",
                            "barge_asset_id": 1,
                            "uom_id": 1,
                            "description": "mason oil",
                            "part_number": null,
                            "model_number": null,
                            "stock_quantity": 35,
                            "critical_level": "high",
                            "threshold": 5,
                            "status": "pending",
                            "reason_for_removal": null,
                            "remark": null,
                            "created_at": "2024-08-08T13:45:39.000000Z",
                            "updated_at": "2024-08-08T13:45:39.000000Z",
                            "inventoryable": {
                                "id": 2,
                                "subscriber_id": 1,
                                "project_id": 1,
                                "barge_id": 1,
                                "deck_id": 1,
                                "vendor_id": 1,
                                "keystore_id": 1,
                                "barge_component_category_id": 1,
                                "location_id": 1,
                                "oil_and_lubricant_type_id": 1,
                                "unit_of_measurement_id": 1,
                                "consumable_deck_category_id": 1,
                                "description": "mason oil",
                                "part_number": "GAR-5674",
                                "model_grade": "LAS-654",
                                "stock_quantity": 50,
                                "threshold": 10,
                                "status_condition": "healthy",
                                "critical_level": "low",
                                "added_by": 1,
                                "date_acquired": "2023-08-25",
                                "waranty_period": "2024-09-28",
                                "status": "active",
                                "remark": "this is work in progress",
                                "created_at": "2024-08-07T14:13:18.000000Z",
                                "updated_at": "2024-08-07T14:13:18.000000Z",
                                "deleted_at": null
                            },
                            "attachements": []
                        }
                    ]
                },
                "vendor_category": null,
                "vendors": [
                    {
                        "id": 1,
                        "subscriber_id": 1,
                        "vendor_category_id": 1,
                        "vendor_name": "TechCorp",
                        "vendor_website": "https://techcorp.com",
                        "vendor_country": "USA",
                        "vendor_phone_number": "+1234567890",
                        "vendor_founded_at": "2000-01-01",
                        "vendor_email": "info@techcorp.com",
                        "vendor_description": "Leading tech company",
                        "vendor_address": "123 Tech Street, Silicon Valley",
                        "status": "active",
                        "created_at": "2024-08-03T12:18:24.000000Z",
                        "updated_at": "2024-08-03T12:18:24.000000Z",
                        "deleted_at": null,
                        "pivot": {
                            "request_for_quotation_id": 1,
                            "vendor_id": 1
                        }
                    },
                    {
                        "id": 2,
                        "subscriber_id": 1,
                        "vendor_category_id": 2,
                        "vendor_name": "AutoWorks",
                        "vendor_website": "https://autoworks.com",
                        "vendor_country": "Germany",
                        "vendor_phone_number": "+9876543210",
                        "vendor_founded_at": "1995-05-15",
                        "vendor_email": "contact@autoworks.com",
                        "vendor_description": "Top automotive parts supplier",
                        "vendor_address": "456 Auto Lane, Berlin",
                        "status": "active",
                        "created_at": "2024-08-03T12:18:24.000000Z",
                        "updated_at": "2024-08-03T12:18:24.000000Z",
                        "deleted_at": null,
                        "pivot": {
                            "request_for_quotation_id": 1,
                            "vendor_id": 2
                        }
                    }
                ]
            }
        ],
        "first_page_url": "http://127.0.0.1:8000/api/v1/procurement/rfq?page%5Bnumber%5D=1",
        "from": 1,
        "last_page": 1,
        "last_page_url": "http://127.0.0.1:8000/api/v1/procurement/rfq?page%5Bnumber%5D=1",
        "links": [
            {
                "url": null,
                "label": "&laquo; Previous",
                "active": false
            },
            {
                "url": "http://127.0.0.1:8000/api/v1/procurement/rfq?page%5Bnumber%5D=1",
                "label": "1",
                "active": true
            },
            {
                "url": null,
                "label": "Next &raquo;",
                "active": false
            }
        ],
        "next_page_url": null,
        "path": "http://127.0.0.1:8000/api/v1/procurement/rfq",
        "per_page": 30,
        "prev_page_url": null,
        "to": 1,
        "total": 1
    }
}